mcsa_daily:
  cron: "0 6 * * *"
  # Use package entrypoint and correct job name
  cmd: "python -m tayfin_screener_jobs jobs run mcsa_screen nasdaq-100"

indicators_hourly:
  cron: "0 * * * *"
  # indicator job and target must match tayfin-indicator config
  cmd: "python -m tayfin_indicator_jobs jobs run vol_sma_compute nasdaq-100"

ohlcv_daily:
  cron: "0 5 * * *"
  # use defined ingestor target name
  cmd: "python -m tayfin_ingestor_jobs jobs run ohlcv nasdaq-100"
